# yml配置文件

## 定义对象/Map集合
#user: # 定义 user对象，里面有name\age\address四个属性
#  name: Tom
#  age: 20
#  address: beijing
#
##定义数组/List/Set
#hobby:  # 定义hobby是一个数组，里面有java\c\game\sport四个元素
#  - java
#  - c
#  - game
#  - sport

#将 application.properties中的配置信息转移到yml中
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: zzy0927
  #文件上传大小配置
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
mybatis:
  configuration:
    # 配置mybatis日志，指定输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰开关
    map-underscore-to-camel-case: true
#阿里云oos配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tHFv35jtEoZSCfeK3hy
    accessKeySecret: d2W1spBIhajkIboyL2qrGHMdcRgZKf
    bucketName: springboot-learn
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug