spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carprogram
    username: root
    password: zzy0927
  #文件上传大小配置
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
mybatis:
  configuration:
    # 配置mybatis日志，指定输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰开关
    map-underscore-to-camel-case: true
